### ISSUE TITLE
Update Help

### ISSUE THREAD

**Issue by Sounak008** [darkk99/aseprite-resources#1]
Do you plan to update the repo incase aseprite updates itself?

**Comment by carnivorecookies** [comment]
The repo will be updated if changes need to be made, i.e:
- Changes to dependencies
- Compiler flags being changed
- I made a mistake in the scripts
Feel free to close if you don't have further questions!

**Comment by Sounak008** [comment]
> The repo will be updated if changes need to be made, i.e:
> 
> * Changes to dependencies
> * Compiler flags being changed
> * I made a mistake in the scripts
>   Feel free to close if you don't have further questions!

Another little question, how can I change the version of aseprite I am installing in the code (the place where it downloads the aseprite source code. Where is it?)

**Comment by carnivorecookies** [comment]
> > The repo will be updated if changes need to be made, i.e:
> > 
> > * Changes to dependencies
> > * Compiler flags being changed
> > * I made a mistake in the scripts
> >   Feel free to close if you don't have further questions!
> 
> Another little question, how can I change the version of aseprite I am installing in the code (the place where it downloads the aseprite source code. Where is it?)

Should be right [here](https://github.com/darkk99/aseprite-resources/blob/main/scripts/lib/install-deps.sh#L33-L36) in `scripts/lib/install-deps.sh`

NOTE: This comment has correct and valid information as of September 22 10:41 AM EST. This information may be wrong in the future, as I plan on re-organizing the scripts.

**Comment by Sounak008** [comment]
Thank you.
